version: '3'
services:


  prometheus:
    image: prom/prometheus:latest
    user: root
    container_name: prometheus
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
    - web
  web:
    image: infracloudio/csvserver:latest
    ports:
    - 9393:9300
    environment:
    - CSVSERVER_BORDER=Orange
    volumes:
    - /root/csvserver/solution/inputFile:/csvserver/inputdata
