version: '3'
services:
  web:
    image: infracloudio/csvserver:latest
    ports:
    - "9393:9300"
    environment:
    - CSVSERVER_BORDER=Orange
    volumes:
    - /root/csvserver/solution/inputFile:/csvserver/inputdata  
